### ISSUE TITLE
UX: View Options

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/mt_ngauruhoe_3js#2]
1) I suggest to label the view options with a label.
2) Reposition them and use their space for the actual title.
3) When the user clicks on a view option it briefly changes its background colour to blue. While I like this visual indication, the black font does not contrast sufficiently on the dark blue. Can you make it light blue rather than dark blue?

**Comment by neon-ninja** [comment]
Do they not have labels for you already?

**Comment by DorisAtCeR** [comment]
I mean a label called "View Options" . Your current view only states the options but not what these options represent.
