### ISSUE TITLE
UX: Mouse Interaction Legend

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/mt_ngauruhoe_3js#3]
It would be helpful to have a little legend for the user to learn what mouse interactions they can do. I like what Bianca did in the Devonport Sealevel visualisation.
![screen shot 2018-07-06 at 2 06 38 pm](https://user-images.githubusercontent.com/26263513/42356428-7f94e9fc-8126-11e8-9944-f2c7d9707299.png)

**Comment by neon-ninja** [comment]
How's this? https://github.com/UoA-eResearch/mt_ngauruhoe_3js/commit/e803e263b76b5e54351468babac40c30dea4b019

**Comment by DorisAtCeR** [comment]
Yes, I like it :-)
